#!/bin/sh

# show all available tmux windows and connect to one
# see also utils/term/tmxcycle

tmuxsel () {
   windows=`tmux lsw -a -F '#{session_name}:#{window_index}' 2>/dev/null`
   set - $windows
   if [ $# -eq 0 ] ; then
       printf "No tmux sessions were found. Press enter or type a session name to start a new session or CTRL-C to exit."
   else
       printf "The following windows are available, select an index:\n"
       i=0
       for w ; do
           i=`expr $i + 1 `
           printf "$i "
           tmux lsw -a -F "#{window_name} #{session_name}:#{window_index}" |sed -ne "s/$w$/${w%:*}/p"
       done
   fi
   read s
   if expr $s \<= $# \& $s \> 0 >/dev/null 2>&1  ; then
       set - $windows
       shift `expr $s - 1`
       session_name=${1%:*}
       window_index=${1#*:}
   else
       session_name=$s
   fi
   if which tmxcycle >/dev/null 2>&1 ; then
       tmxcycle $session_name $window_index
   elif [ -n "$window_index" ] ; then
       tmux at -t $session_name \; selectw -t $window_index
   else
       tmux new -s $session_name
   fi
}

for t in rxvt rxvt-unicode screen xterm  ; do
   if [ "x$TERM" = "x$t" ] ; then
      tmuxsel "$@" ; exit $?
   fi
done

if [ -n "$DISPLAY" ] ; then
	exec x-terminal-emulator -tn xterm -e tmuxsel
fi
